In [2]:
import cv2
import numpy as np
import os

In [4]:
# Creating 5 folders as part of the project objective
for i in range(1,6):
    os.mkdir(r"Python Class\Open_CV\{}".format(i))

In [5]:
# Identifying the folders and files in the path
path, dirs, files = next(os.walk(r"C:\Users\vivek\Python Class\Open_CV"))

In [4]:
# Captruing the live feed and converting it into individual frames and using 'a' to stop feeding into the current folder 
# and move on to the next folders until all the folders are done
vi=cv2.VideoCapture(0)
count=0
for i in dirs:
    while True:
        count+=1
        su,img=vi.read()    
        cv2.imshow("video",img)
        cv2.imwrite(r"Python Class\Open_CV\{}\{}.jpg".format(i,count),img)
        if cv2.waitKey(1)==ord("a"):
            break
    cv2.destroyAllWindows()

In [10]:
# Converting each image of the folder into a 1d-array by flattening the 3d-matrix of each cell/pixel and then converting it to list 
x=[]
y=[]
for i in dirs:
    _, _, img =next(os.walk(r"Python Class\Open_CV\{}".format(i)))
    for j in img:
        y.append(int(j.split('.')[0]))
        x.append(cv2.imread(r"Python Class\Open_CV\{}\{}".format(i,j)).flatten().tolist())

In [14]:
# Creating a Data Frame for the colour images with the file name as the index
color=pd.DataFrame(x,index=y)

In [19]:
color

,0,1,2,3,4,5,6,7,8,9,...,921590,921591,921592,921593,921594,921595,921596,921597,921598,921599
1,251,251,251,251,251,251,251,251,251,251,...,91,147,121,91,146,121,89,159,134,102
10,251,251,251,251,251,251,251,251,251,251,...,69,136,116,59,139,119,61,144,125,64
100,251,251,251,251,251,251,251,251,251,251,...,55,73,70,49,68,68,44,72,75,49
101,251,251,251,251,251,251,251,251,251,251,...,55,90,70,52,88,72,49,82,67,41
102,251,251,251,251,251,251,251,251,251,251,...,59,87,71,48,88,71,45,89,72,45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,252,252,252,252,252,252,252,252,252,252,...,188,239,225,189,247,232,200,249,235,206
443,252,252,252,252,252,252,252,252,252,252,...,194,244,229,197,239,225,196,252,240,212
444,252,252,252,252,252,252,252,252,252,252,...,204,250,229,207,241,224,205,250,234,217
445,252,252,252,252,252,252,252,252,252,252,...,208,249,233,210,246,229,208,251,234,215
446,252,252,252,252,252,252,252,252,252,252,...,215,243,236,216,244,237,218,250,244,225

In [27]:
y

[1,
 10,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 11,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 12,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 13,
 130,
 131,
 132,
 133,
 134,
 135,
 14,
 15,
 16,
 17,
 18,
 19,
 2,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 3,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 4,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 5,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 6,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 7,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 8,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 9,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498]

In [24]:
# Converting the 3d-matrix into 2d-matrix(gray scale) images and then into a 1d-array by flattening the 3d-matrix of each cell/pixel
#  and converting it to list 
a=[]
b=[]
for i in dirs:
    _, _, img =next(os.walk(r"Python Class\Open_CV\{}".format(i)))
    for j in img:
        a.append(int(j.split('.')[0]))
        b.append(cv2.imread(r"Python Class\Open_CV\{}\{}".format(i,j),0).flatten().tolist())

In [25]:
# Creating a Data Frame for the gray scale images with the file name as the index
import pandas as pd
gray=pd.DataFrame(b, index=a)

In [26]:
gray

,0,1,2,3,4,5,6,7,8,9,...,307190,307191,307192,307193,307194,307195,307196,307197,307198,307199
1,251,251,251,251,251,251,251,251,251,251,...,81,72,75,78,122,129,113,115,114,127
10,251,251,251,251,251,251,251,251,251,251,...,89,80,49,60,95,119,108,101,104,109
100,251,251,251,251,251,251,251,251,251,251,...,91,36,35,40,54,65,68,64,61,67
101,251,251,251,251,251,251,251,251,251,251,...,91,40,29,37,52,67,68,67,67,61
102,251,251,251,251,251,251,251,251,251,251,...,96,57,28,41,52,63,74,66,65,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
442,252,252,252,252,252,252,252,252,252,252,...,189,192,194,192,214,227,217,216,224,228
443,252,252,252,252,252,252,252,252,252,252,...,195,198,198,200,213,223,221,221,218,233
444,252,252,252,252,252,252,252,252,252,252,...,197,196,198,198,219,226,225,225,220,231
445,252,252,252,252,252,252,252,252,252,252,...,199,202,203,209,225,225,229,228,225,230
446,252,252,252,252,252,252,252,252,252,252,...,200,201,204,209,231,239,232,231,232,239